---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-storage
  labels:
    app.kubernetes.io/name: storage
    app.kubernetes.io/instance: storage-service
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: provider
