/*
Copyright The Akash Network Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v2beta2

import (
	context "context"

	akashnetworkv2beta2 "github.com/akash-network/provider/pkg/apis/akash.network/v2beta2"
	applyconfigurationakashnetworkv2beta2 "github.com/akash-network/provider/pkg/client/applyconfiguration/akash.network/v2beta2"
	scheme "github.com/akash-network/provider/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VolumesGetter has a method to return a VolumeInterface.
// A group's client should implement this interface.
type VolumesGetter interface {
	Volumes(namespace string) VolumeInterface
}

// VolumeInterface has methods to work with Volume resources.
type VolumeInterface interface {
	Create(ctx context.Context, volume *akashnetworkv2beta2.Volume, opts v1.CreateOptions) (*akashnetworkv2beta2.Volume, error)
	Update(ctx context.Context, volume *akashnetworkv2beta2.Volume, opts v1.UpdateOptions) (*akashnetworkv2beta2.Volume, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, volume *akashnetworkv2beta2.Volume, opts v1.UpdateOptions) (*akashnetworkv2beta2.Volume, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*akashnetworkv2beta2.Volume, error)
	List(ctx context.Context, opts v1.ListOptions) (*akashnetworkv2beta2.VolumeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *akashnetworkv2beta2.Volume, err error)
	Apply(ctx context.Context, volume *applyconfigurationakashnetworkv2beta2.VolumeApplyConfiguration, opts v1.ApplyOptions) (result *akashnetworkv2beta2.Volume, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, volume *applyconfigurationakashnetworkv2beta2.VolumeApplyConfiguration, opts v1.ApplyOptions) (result *akashnetworkv2beta2.Volume, err error)
	VolumeExpansion
}

// volumes implements VolumeInterface
type volumes struct {
	*gentype.ClientWithListAndApply[*akashnetworkv2beta2.Volume, *akashnetworkv2beta2.VolumeList, *applyconfigurationakashnetworkv2beta2.VolumeApplyConfiguration]
}

// newVolumes returns a Volumes
func newVolumes(c *AkashV2beta2Client, namespace string) *volumes {
	return &volumes{
		gentype.NewClientWithListAndApply[*akashnetworkv2beta2.Volume, *akashnetworkv2beta2.VolumeList, *applyconfigurationakashnetworkv2beta2.VolumeApplyConfiguration](
			"volumes",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *akashnetworkv2beta2.Volume { return &akashnetworkv2beta2.Volume{} },
			func() *akashnetworkv2beta2.VolumeList { return &akashnetworkv2beta2.VolumeList{} },
		),
	}
}
