/*
Copyright The Akash Network Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2beta2

// ManifestServicePermissionsApplyConfiguration represents a declarative configuration of the ManifestServicePermissions type for use
// with apply.
type ManifestServicePermissionsApplyConfiguration struct {
	Read   []string `json:"read,omitempty"`
	Write  []string `json:"write,omitempty"`
	Delete []string `json:"delete,omitempty"`
}

// ManifestServicePermissionsApplyConfiguration constructs a declarative configuration of the ManifestServicePermissions type for use with
// apply.
func ManifestServicePermissions() *ManifestServicePermissionsApplyConfiguration {
	return &ManifestServicePermissionsApplyConfiguration{}
}

// WithRead adds the given value to the Read field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Read field.
func (b *ManifestServicePermissionsApplyConfiguration) WithRead(values ...string) *ManifestServicePermissionsApplyConfiguration {
	for i := range values {
		b.Read = append(b.Read, values[i])
	}
	return b
}

// WithWrite adds the given value to the Write field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Write field.
func (b *ManifestServicePermissionsApplyConfiguration) WithWrite(values ...string) *ManifestServicePermissionsApplyConfiguration {
	for i := range values {
		b.Write = append(b.Write, values[i])
	}
	return b
}

// WithDelete adds the given value to the Delete field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Delete field.
func (b *ManifestServicePermissionsApplyConfiguration) WithDelete(values ...string) *ManifestServicePermissionsApplyConfiguration {
	for i := range values {
		b.Delete = append(b.Delete, values[i])
	}
	return b
}
