/*
Copyright The Akash Network Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2beta2

// VolumeSpecApplyConfiguration represents a declarative configuration of the VolumeSpec type for use
// with apply.
type VolumeSpecApplyConfiguration struct {
	Owner     *string                          `json:"owner,omitempty"`
	VID       *string                          `json:"vid,omitempty"`
	GroupID   *VolumeGroupIDApplyConfiguration `json:"groupId,omitempty"`
	Class     *string                          `json:"class,omitempty"`
	Size      *string                          `json:"size,omitempty"`
	Reclaim   *string                          `json:"reclaim,omitempty"`
	Retention *string                          `json:"retention,omitempty"`
	LeaseID   *LeaseIDApplyConfiguration       `json:"leaseId,omitempty"`
}

// VolumeSpecApplyConfiguration constructs a declarative configuration of the VolumeSpec type for use with
// apply.
func VolumeSpec() *VolumeSpecApplyConfiguration {
	return &VolumeSpecApplyConfiguration{}
}

// WithOwner sets the Owner field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Owner field is set to the value of the last call.
func (b *VolumeSpecApplyConfiguration) WithOwner(value string) *VolumeSpecApplyConfiguration {
	b.Owner = &value
	return b
}

// WithVID sets the VID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VID field is set to the value of the last call.
func (b *VolumeSpecApplyConfiguration) WithVID(value string) *VolumeSpecApplyConfiguration {
	b.VID = &value
	return b
}

// WithGroupID sets the GroupID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GroupID field is set to the value of the last call.
func (b *VolumeSpecApplyConfiguration) WithGroupID(value *VolumeGroupIDApplyConfiguration) *VolumeSpecApplyConfiguration {
	b.GroupID = value
	return b
}

// WithClass sets the Class field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Class field is set to the value of the last call.
func (b *VolumeSpecApplyConfiguration) WithClass(value string) *VolumeSpecApplyConfiguration {
	b.Class = &value
	return b
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *VolumeSpecApplyConfiguration) WithSize(value string) *VolumeSpecApplyConfiguration {
	b.Size = &value
	return b
}

// WithReclaim sets the Reclaim field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reclaim field is set to the value of the last call.
func (b *VolumeSpecApplyConfiguration) WithReclaim(value string) *VolumeSpecApplyConfiguration {
	b.Reclaim = &value
	return b
}

// WithRetention sets the Retention field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Retention field is set to the value of the last call.
func (b *VolumeSpecApplyConfiguration) WithRetention(value string) *VolumeSpecApplyConfiguration {
	b.Retention = &value
	return b
}

// WithLeaseID sets the LeaseID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LeaseID field is set to the value of the last call.
func (b *VolumeSpecApplyConfiguration) WithLeaseID(value *LeaseIDApplyConfiguration) *VolumeSpecApplyConfiguration {
	b.LeaseID = value
	return b
}
