/*
Copyright The Akash Network Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2beta2

import (
	akashnetworkv2beta2 "github.com/akash-network/provider/pkg/apis/akash.network/v2beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// VolumeStatusApplyConfiguration represents a declarative configuration of the VolumeStatus type for use
// with apply.
type VolumeStatusApplyConfiguration struct {
	Phase         *akashnetworkv2beta2.VolumePhase `json:"phase,omitempty"`
	PVName        *string                          `json:"pvName,omitempty"`
	AttachedLease *string                          `json:"attachedLease,omitempty"`
	RetainedUntil *v1.Time                         `json:"retainedUntil,omitempty"`
}

// VolumeStatusApplyConfiguration constructs a declarative configuration of the VolumeStatus type for use with
// apply.
func VolumeStatus() *VolumeStatusApplyConfiguration {
	return &VolumeStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *VolumeStatusApplyConfiguration) WithPhase(value akashnetworkv2beta2.VolumePhase) *VolumeStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithPVName sets the PVName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PVName field is set to the value of the last call.
func (b *VolumeStatusApplyConfiguration) WithPVName(value string) *VolumeStatusApplyConfiguration {
	b.PVName = &value
	return b
}

// WithAttachedLease sets the AttachedLease field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AttachedLease field is set to the value of the last call.
func (b *VolumeStatusApplyConfiguration) WithAttachedLease(value string) *VolumeStatusApplyConfiguration {
	b.AttachedLease = &value
	return b
}

// WithRetainedUntil sets the RetainedUntil field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetainedUntil field is set to the value of the last call.
func (b *VolumeStatusApplyConfiguration) WithRetainedUntil(value v1.Time) *VolumeStatusApplyConfiguration {
	b.RetainedUntil = &value
	return b
}
